version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    groups:
      dotnet:
        patterns: ["Microsoft.*", "System.*"]

  - package-ecosystem: docker
    directories: ["/src/Ssabba.Web", "/docs"]
    schedule:
      interval: weekly

  - package-ecosystem: docker-compose
    directory: "/deploy"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: monthly
