// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ssabba.Infrastructure;

#nullable disable

namespace Ssabba.Infrastructure.Migrations
{
    [DbContext(typeof(SsabbaDbContext))]
    [Migration("20260812095240_AddVenuesAndFormats")]
    partial class AddVenuesAndFormats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ssabba.Domain.Entities.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("PublicKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublicKeyId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CommunityInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AcceptedByPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByPlayerId");

                    b.HasIndex("InvitedByMemberId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("CommunityId", "ExpiresAt");

                    b.ToTable("CommunityInvites");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CommunityLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("SharedSecretHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SourceCommunityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetCommunityUri")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("TargetName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("TargetPublicKeyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceCommunityId", "TargetCommunityUri")
                        .IsUnique();

                    b.ToTable("CommunityLinks");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CommunityMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RatingDeviation")
                        .HasColumnType("integer");

                    b.Property<int>("ReliabilityScore")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("CommunityId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("CommunityId", "Rating");

                    b.ToTable("CommunityMembers");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasLighting")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxTeamSize")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("NetHeightCm")
                        .HasColumnType("integer");

                    b.Property<int>("Surface")
                        .HasColumnType("integer");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique();

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CourtReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CostMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HeldByCommunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HeldByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeldByCommunityId");

                    b.HasIndex("HeldByMemberId");

                    b.HasIndex("CourtId", "StartsAt");

                    b.ToTable("CourtReservations");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Format", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultPointsPerSet")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultSetsToWin")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultTiebreakPoints")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultWinBy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("PlayersPerSide")
                        .HasColumnType("integer");

                    b.Property<int>("RatingWeightPercent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Formats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0195f000-0000-7000-8000-000000000002"),
                            Code = 2,
                            DefaultPointsPerSet = 21,
                            DefaultSetsToWin = 2,
                            DefaultTiebreakPoints = 15,
                            DefaultWinBy = 2,
                            Name = "2v2",
                            PlayersPerSide = 2,
                            RatingWeightPercent = 100
                        },
                        new
                        {
                            Id = new Guid("0195f000-0000-7000-8000-000000000003"),
                            Code = 3,
                            DefaultPointsPerSet = 21,
                            DefaultSetsToWin = 2,
                            DefaultTiebreakPoints = 15,
                            DefaultWinBy = 2,
                            Name = "3v3",
                            PlayersPerSide = 3,
                            RatingWeightPercent = 85
                        },
                        new
                        {
                            Id = new Guid("0195f000-0000-7000-8000-000000000004"),
                            Code = 4,
                            DefaultPointsPerSet = 21,
                            DefaultSetsToWin = 2,
                            DefaultTiebreakPoints = 15,
                            DefaultWinBy = 2,
                            Name = "4v4",
                            PlayersPerSide = 4,
                            RatingWeightPercent = 70
                        },
                        new
                        {
                            Id = new Guid("0195f000-0000-7000-8000-000000000005"),
                            Code = 5,
                            DefaultPointsPerSet = 25,
                            DefaultSetsToWin = 2,
                            DefaultTiebreakPoints = 15,
                            DefaultWinBy = 2,
                            Name = "5v5",
                            PlayersPerSide = 5,
                            RatingWeightPercent = 60
                        },
                        new
                        {
                            Id = new Guid("0195f000-0000-7000-8000-000000000006"),
                            Code = 6,
                            DefaultPointsPerSet = 25,
                            DefaultSetsToWin = 2,
                            DefaultTiebreakPoints = 15,
                            DefaultWinBy = 2,
                            Name = "6v6",
                            PlayersPerSide = 6,
                            RatingWeightPercent = 50
                        });
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.JoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByMemberId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("CommunityId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_JoinRequests_CommunityId_PlayerId_Pending")
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("JoinRequests");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocationNote")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CourtId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("PlayedAt");

                    b.HasIndex("TournamentId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.MatchSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayPoints")
                        .HasColumnType("integer");

                    b.Property<int>("HomePoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "Number")
                        .IsUnique();

                    b.ToTable("MatchSets");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PreferredTimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("SubjectId")
                        .IsUnique()
                        .HasFilter("\"SubjectId\" IS NOT NULL AND \"DeletedAt\" IS NULL");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.PlayerContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Kind", "Value")
                        .IsUnique();

                    b.ToTable("PlayerContacts");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLeftHanded")
                        .HasColumnType("boolean");

                    b.Property<int?>("PlayingSince")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredPositions")
                        .HasColumnType("integer");

                    b.Property<int?>("SelfRatedLevel")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.RuleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("LetServeAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PointsPerSet")
                        .HasColumnType("integer");

                    b.Property<int>("SetsToWin")
                        .HasColumnType("integer");

                    b.Property<int?>("SwitchEveryPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TiebreakPoints")
                        .HasColumnType("integer");

                    b.Property<int>("WinBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("CommunityId", "FormatId")
                        .IsUnique()
                        .HasDatabaseName("IX_RuleSets_CommunityId_FormatId_Default")
                        .HasFilter("\"IsDefault\"");

                    b.ToTable("RuleSets");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId")
                        .IsUnique()
                        .HasDatabaseName("IX_Seasons_CommunityId_Current")
                        .HasFilter("\"IsCurrent\"");

                    b.HasIndex("CommunityId", "StartsOn");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Access")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("OwnerCommunityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerCommunityId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CommunityInvite", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Player", "AcceptedByPlayer")
                        .WithMany()
                        .HasForeignKey("AcceptedByPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "InvitedByMember")
                        .WithMany()
                        .HasForeignKey("InvitedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcceptedByPlayer");

                    b.Navigation("Community");

                    b.Navigation("InvitedByMember");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CommunityLink", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "SourceCommunity")
                        .WithMany()
                        .HasForeignKey("SourceCommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceCommunity");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CommunityMember", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany("Members")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Player", "Player")
                        .WithMany("Memberships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Court", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Venue", "Venue")
                        .WithMany("Courts")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CourtReservation", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Community", "HeldByCommunity")
                        .WithMany()
                        .HasForeignKey("HeldByCommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "HeldByMember")
                        .WithMany()
                        .HasForeignKey("HeldByMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Court");

                    b.Navigation("HeldByCommunity");

                    b.Navigation("HeldByMember");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.JoinRequest", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "DecidedByMember")
                        .WithMany()
                        .HasForeignKey("DecidedByMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("DecidedByMember");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Match", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AwayTeam");

                    b.Navigation("Court");

                    b.Navigation("HomeTeam");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.MatchSet", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Match", "Match")
                        .WithMany("Sets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.PlayerContact", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Player", "Player")
                        .WithMany("Contacts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.PlayerProfile", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Player", "Player")
                        .WithOne("Profile")
                        .HasForeignKey("Ssabba.Domain.Entities.PlayerProfile", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.RuleSet", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Format", "Format")
                        .WithMany()
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Format");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Season", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany("Seasons")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Player", "Player")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Venue", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "OwnerCommunity")
                        .WithMany()
                        .HasForeignKey("OwnerCommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerCommunity");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Community", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Match", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Player", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Memberships");

                    b.Navigation("Profile");

                    b.Navigation("TeamMemberships");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Venue", b =>
                {
                    b.Navigation("Courts");
                });
#pragma warning restore 612, 618
        }
    }
}
