// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ssabba.Infrastructure;

#nullable disable

namespace Ssabba.Infrastructure.Migrations
{
    [DbContext(typeof(SsabbaDbContext))]
    [Migration("20260812095956_AddMatchDepth")]
    partial class AddMatchDepth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ssabba.Domain.Entities.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("PublicKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublicKeyId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CommunityInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AcceptedByPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByPlayerId");

                    b.HasIndex("InvitedByMemberId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("CommunityId", "ExpiresAt");

                    b.ToTable("CommunityInvites");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CommunityLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("SharedSecretHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SourceCommunityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetCommunityUri")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("TargetName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("TargetPublicKeyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceCommunityId", "TargetCommunityUri")
                        .IsUnique();

                    b.ToTable("CommunityLinks");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CommunityMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RatingDeviation")
                        .HasColumnType("integer");

                    b.Property<int>("ReliabilityScore")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("CommunityId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("CommunityId", "Rating");

                    b.ToTable("CommunityMembers");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasLighting")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxTeamSize")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("NetHeightCm")
                        .HasColumnType("integer");

                    b.Property<int>("Surface")
                        .HasColumnType("integer");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique();

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CourtReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CostMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HeldByCommunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HeldByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeldByCommunityId");

                    b.HasIndex("HeldByMemberId");

                    b.HasIndex("CourtId", "StartsAt");

                    b.ToTable("CourtReservations");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Format", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultPointsPerSet")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultSetsToWin")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultTiebreakPoints")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultWinBy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("PlayersPerSide")
                        .HasColumnType("integer");

                    b.Property<int>("RatingWeightPercent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Formats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0195f000-0000-7000-8000-000000000002"),
                            Code = 2,
                            DefaultPointsPerSet = 21,
                            DefaultSetsToWin = 2,
                            DefaultTiebreakPoints = 15,
                            DefaultWinBy = 2,
                            Name = "2v2",
                            PlayersPerSide = 2,
                            RatingWeightPercent = 100
                        },
                        new
                        {
                            Id = new Guid("0195f000-0000-7000-8000-000000000003"),
                            Code = 3,
                            DefaultPointsPerSet = 21,
                            DefaultSetsToWin = 2,
                            DefaultTiebreakPoints = 15,
                            DefaultWinBy = 2,
                            Name = "3v3",
                            PlayersPerSide = 3,
                            RatingWeightPercent = 85
                        },
                        new
                        {
                            Id = new Guid("0195f000-0000-7000-8000-000000000004"),
                            Code = 4,
                            DefaultPointsPerSet = 21,
                            DefaultSetsToWin = 2,
                            DefaultTiebreakPoints = 15,
                            DefaultWinBy = 2,
                            Name = "4v4",
                            PlayersPerSide = 4,
                            RatingWeightPercent = 70
                        },
                        new
                        {
                            Id = new Guid("0195f000-0000-7000-8000-000000000005"),
                            Code = 5,
                            DefaultPointsPerSet = 25,
                            DefaultSetsToWin = 2,
                            DefaultTiebreakPoints = 15,
                            DefaultWinBy = 2,
                            Name = "5v5",
                            PlayersPerSide = 5,
                            RatingWeightPercent = 60
                        },
                        new
                        {
                            Id = new Guid("0195f000-0000-7000-8000-000000000006"),
                            Code = 6,
                            DefaultPointsPerSet = 25,
                            DefaultSetsToWin = 2,
                            DefaultTiebreakPoints = 15,
                            DefaultWinBy = 2,
                            Name = "6v6",
                            PlayersPerSide = 6,
                            RatingWeightPercent = 50
                        });
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.JoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByMemberId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("CommunityId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_JoinRequests_CommunityId_PlayerId_Pending")
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("JoinRequests");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<int?>("BracketSlot")
                        .HasColumnType("integer");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocationNote")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PointsPerSet")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RatingAppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RecordedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RuleSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SetsToWin")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TiebreakPoints")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TournamentRound")
                        .HasColumnType("integer");

                    b.Property<int>("WinBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CourtId");

                    b.HasIndex("FormatId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("PlayedAt");

                    b.HasIndex("RecordedByMemberId");

                    b.HasIndex("RuleSetId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("CommunityId", "PlayedAt");

                    b.HasIndex("CommunityId", "Status", "RatingAppliedAt");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.MatchAppearance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSubstitute")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("RatingAfter")
                        .HasColumnType("integer");

                    b.Property<int>("RatingBefore")
                        .HasColumnType("integer");

                    b.Property<int>("RatingDelta")
                        .HasColumnType("integer");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("MemberId", "MatchId");

                    b.ToTable("MatchAppearances");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.MatchDispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RaisedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Resolution")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaisedByMemberId");

                    b.HasIndex("ResolvedByMemberId");

                    b.HasIndex("MatchId", "Status");

                    b.ToTable("MatchDisputes");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.MatchSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayPoints")
                        .HasColumnType("integer");

                    b.Property<int>("HomePoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "Number")
                        .IsUnique();

                    b.ToTable("MatchSets");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PreferredTimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("SubjectId")
                        .IsUnique()
                        .HasFilter("\"SubjectId\" IS NOT NULL AND \"DeletedAt\" IS NULL");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.PlayerContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Kind", "Value")
                        .IsUnique();

                    b.ToTable("PlayerContacts");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.PlayerFormatStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("Matches")
                        .HasColumnType("integer");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("PointsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("PointsFor")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<int>("SetsLost")
                        .HasColumnType("integer");

                    b.Property<int>("SetsWon")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("MemberId", "FormatId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlayerFormatStats_MemberId_FormatId_AllTime")
                        .HasFilter("\"SeasonId\" IS NULL");

                    b.HasIndex("MemberId", "FormatId", "SeasonId")
                        .IsUnique()
                        .HasFilter("\"SeasonId\" IS NOT NULL");

                    b.ToTable("PlayerFormatStats");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLeftHanded")
                        .HasColumnType("boolean");

                    b.Property<int?>("PlayingSince")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredPositions")
                        .HasColumnType("integer");

                    b.Property<int?>("SelfRatedLevel")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Poll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowMultiple")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ClosesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ResultSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByMemberId");

                    b.HasIndex("ResultSessionId");

                    b.HasIndex("CommunityId", "Status");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.PollOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("PollId", "SortOrder");

                    b.ToTable("PollOptions");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.RuleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("LetServeAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PointsPerSet")
                        .HasColumnType("integer");

                    b.Property<int>("SetsToWin")
                        .HasColumnType("integer");

                    b.Property<int?>("SwitchEveryPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TiebreakPoints")
                        .HasColumnType("integer");

                    b.Property<int>("WinBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("CommunityId", "FormatId")
                        .IsUnique()
                        .HasDatabaseName("IX_RuleSets_CommunityId_FormatId_Default")
                        .HasFilter("\"IsDefault\"");

                    b.ToTable("RuleSets");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId")
                        .IsUnique()
                        .HasDatabaseName("IX_Seasons_CommunityId_Current")
                        .HasFilter("\"IsCurrent\"");

                    b.HasIndex("CommunityId", "StartsOn");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<long>("CostPerPlayerMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MinPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OrganizerMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RuleSetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("OrganizerMemberId");

                    b.HasIndex("RuleSetId");

                    b.HasIndex("CommunityId", "StartsAt");

                    b.HasIndex("CommunityId", "Status");

                    b.HasIndex("TemplateId", "StartsAt")
                        .IsUnique()
                        .HasFilter("\"TemplateId\" IS NOT NULL");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.SessionParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attendance")
                        .HasColumnType("integer");

                    b.Property<Guid?>("IsGuestOfMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Response")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WaitlistPosition")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsGuestOfMemberId");

                    b.HasIndex("MemberId");

                    b.HasIndex("SessionId", "MemberId")
                        .IsUnique();

                    b.ToTable("SessionParticipants");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.SessionTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultRuleSetId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("GenerateAheadDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Rrule")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<TimeOnly>("StartTimeLocal")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("DefaultRuleSetId");

                    b.HasIndex("CommunityId", "IsActive");

                    b.ToTable("SessionTemplates");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdHoc")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId", "IsAdHoc");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("TeamId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("RuleSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("RuleSetId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("VenueId");

                    b.HasIndex("CommunityId", "StartsOn");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.TournamentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("FinalRank")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Seed")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentId", "TeamId")
                        .IsUnique();

                    b.ToTable("TournamentEntries");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Access")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("OwnerCommunityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerCommunityId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CastAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PollOptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("PollOptionId", "MemberId")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CommunityInvite", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Player", "AcceptedByPlayer")
                        .WithMany()
                        .HasForeignKey("AcceptedByPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "InvitedByMember")
                        .WithMany()
                        .HasForeignKey("InvitedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcceptedByPlayer");

                    b.Navigation("Community");

                    b.Navigation("InvitedByMember");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CommunityLink", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "SourceCommunity")
                        .WithMany()
                        .HasForeignKey("SourceCommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceCommunity");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CommunityMember", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany("Members")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Player", "Player")
                        .WithMany("Memberships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Court", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Venue", "Venue")
                        .WithMany("Courts")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.CourtReservation", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Community", "HeldByCommunity")
                        .WithMany()
                        .HasForeignKey("HeldByCommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "HeldByMember")
                        .WithMany()
                        .HasForeignKey("HeldByMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Court");

                    b.Navigation("HeldByCommunity");

                    b.Navigation("HeldByMember");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.JoinRequest", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "DecidedByMember")
                        .WithMany()
                        .HasForeignKey("DecidedByMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("DecidedByMember");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Match", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.Format", "Format")
                        .WithMany()
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "RecordedByMember")
                        .WithMany()
                        .HasForeignKey("RecordedByMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.RuleSet", "RuleSet")
                        .WithMany()
                        .HasForeignKey("RuleSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AwayTeam");

                    b.Navigation("Community");

                    b.Navigation("Court");

                    b.Navigation("Format");

                    b.Navigation("HomeTeam");

                    b.Navigation("RecordedByMember");

                    b.Navigation("RuleSet");

                    b.Navigation("Season");

                    b.Navigation("Session");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.MatchAppearance", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Match", "Match")
                        .WithMany("Appearances")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Member");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.MatchDispute", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "RaisedByMember")
                        .WithMany()
                        .HasForeignKey("RaisedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "ResolvedByMember")
                        .WithMany()
                        .HasForeignKey("ResolvedByMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Match");

                    b.Navigation("RaisedByMember");

                    b.Navigation("ResolvedByMember");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.MatchSet", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Match", "Match")
                        .WithMany("Sets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.PlayerContact", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Player", "Player")
                        .WithMany("Contacts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.PlayerFormatStat", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Format", "Format")
                        .WithMany()
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Format");

                    b.Navigation("Member");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.PlayerProfile", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Player", "Player")
                        .WithOne("Profile")
                        .HasForeignKey("Ssabba.Domain.Entities.PlayerProfile", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Poll", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("CreatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Session", "ResultSession")
                        .WithMany()
                        .HasForeignKey("ResultSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Community");

                    b.Navigation("CreatedByMember");

                    b.Navigation("ResultSession");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.PollOption", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.RuleSet", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Format", "Format")
                        .WithMany()
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Format");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Season", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany("Seasons")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Session", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "OrganizerMember")
                        .WithMany()
                        .HasForeignKey("OrganizerMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.RuleSet", "RuleSet")
                        .WithMany()
                        .HasForeignKey("RuleSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.SessionTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Community");

                    b.Navigation("Court");

                    b.Navigation("OrganizerMember");

                    b.Navigation("RuleSet");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.SessionParticipant", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "IsGuestOfMember")
                        .WithMany()
                        .HasForeignKey("IsGuestOfMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Session", "Session")
                        .WithMany("Participants")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IsGuestOfMember");

                    b.Navigation("Member");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.SessionTemplate", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.RuleSet", "DefaultRuleSet")
                        .WithMany()
                        .HasForeignKey("DefaultRuleSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Community");

                    b.Navigation("Court");

                    b.Navigation("DefaultRuleSet");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Team", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Player", "Player")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Tournament", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Format", "Format")
                        .WithMany()
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.RuleSet", "RuleSet")
                        .WithMany()
                        .HasForeignKey("RuleSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ssabba.Domain.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Community");

                    b.Navigation("Format");

                    b.Navigation("RuleSet");

                    b.Navigation("Season");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.TournamentEntry", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Entries")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Venue", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.Community", "OwnerCommunity")
                        .WithMany()
                        .HasForeignKey("OwnerCommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerCommunity");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Vote", b =>
                {
                    b.HasOne("Ssabba.Domain.Entities.CommunityMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssabba.Domain.Entities.PollOption", "PollOption")
                        .WithMany("Votes")
                        .HasForeignKey("PollOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("PollOption");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Community", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Match", b =>
                {
                    b.Navigation("Appearances");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Player", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Memberships");

                    b.Navigation("Profile");

                    b.Navigation("TeamMemberships");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Poll", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.PollOption", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Session", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Ssabba.Domain.Entities.Venue", b =>
                {
                    b.Navigation("Courts");
                });
#pragma warning restore 612, 618
        }
    }
}
